
theme: jekyll-theme-minimal
  layout: profile
  style: topbar
  title: Holly Chen
  user_image: /docs/assets/profile.jpg
  # logo:
  description: Mechanical Engineer | Biomechanics | Product Design 
  # show_downloads: 


